name: amazon-braket-sdk-docs

channels:
  - conda-forge

dependencies:
  - python==3.11
  - pip
  - myst-parser
  - docutils >=0.18.1,<0.19
  - sphinx==7.2.4
  - sphinx-rtd-theme
  - sphinxcontrib-apidoc
  - jupyterlab >=3.5.3,<3.6
  - jupyterlite-core >=0.1.0,<0.2.0
  - empack >=3.1.0
  - pydantic 
  - pydantic-core
  - typing-extensions
  - annotated-types
  - pip:
    - jupyterlite-sphinx >=0.9.1
    - jupyterlite-xeus-python==0.9.4
    - ..